name: Development Release

on:
  push:
    branches:
      - devs

jobs:
  generate_dev_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.taggerDev.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Development Version
        id: taggerDev
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: devs
          TAG_CONTEXT: branch
          PRESET_TYPE: dev

  create_github_release:
    needs: generate_dev_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.generate_dev_tag.outputs.new_tag }}
          name: Release ${{ needs.generate_dev_tag.outputs.new_tag }}
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: true
          token: ${{ secrets.PAT }}

      - name: Echo Release Info
        run: |
          echo "Created development release: ${{ needs.generate_dev_tag.outputs.new_tag }}"
          echo "Environment: development"